title: The Last Black Box
markdown: GFM
plugins:
    - jekyll-relative-links
relative_links:
    enabled: true
    collections: true
include:
    - README.md
    - _images/
 
theme: jekyll-theme-hacker
